language: php
php:
  - 7.0
  - nightly

script:
  - phpize
  - ./configure
  - make
  - REPORT_EXIT_STATUS=1 TEST_PHP_ARGS="-q --show-diff" make test

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/428fac7bd9f4b867c347
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
